# This won't run as a standalone docker-compose as the service is intentionally missing 'depends_on'.
# Moreover this docker-compose is only intended for the integration testing.
services:
  helloservice:
    image: kvalitetsit/kithugs:latest
    environment:
      - APP_DB_URL=jdbc:mariadb://host.docker.internal:3306/hellodb
      - APP_DB_USERNAME=hellouser
      - APP_DB_PASSWORD=secret1234
    extra_hosts:
      - "host.docker.internal:host-gateway"