version: '2.1'
services:
   mariadb:
     image: mariadb:10.6
     environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=hellodb
      - MYSQL_USER=hellouser
      - MYSQL_PASSWORD=secret1234
     healthcheck:
      test: mysql --user=hellouser --password=secret1234 -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10
   helloservice:
     image: kvalitetsit/kithugs:latest
     environment:
      - jdbc_url=jdbc:mariadb://mariadb:3306/hellodb
      - jdbc_user=hellouser
      - jdbc_pass=secret1234
      - usercontext_header_name=X-Test-Auth

      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation

      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
     depends_on:
      mariadb:
       condition: service_healthy
     ports: 
      - 8080:8080
   documenatation-and-test:
     image: kvalitetsit/kithugs-documentation:latest
     environment:
      - BASE_URL=/test
      - 'SERVER_URLS=[{"url": "http://localhost:8080", "name": "HelloService"}]'
     ports:
      - 80:8080
