openapi: 3.0.0
info:
  title: Kithugs
  description: API description for VDX SMS Gateway.
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: Sms
    description: SMS related operations

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /sms/v1/meeting/{uuid}:
    get:
      tags:
        - Sms
      summary: Get status for sms delivery
      description: Get status for SMS delivery. Can be used to get information abput delivery status of the sms.
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
          description: Meeting uuid.
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/smsStatus'
    post:
      tags:
        - Sms
      summary: Send SMS
      description: Send SMS
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: UUID for VDX meeting.
      requestBody:
        description: SMS message and phone number
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/smsRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/smsResponse'

  /sms/v1/callback:
    get:
      tags:
        - Callback service
      summary: Callback service used by SMS gateway.
      description: Callback service used by SMS gateway provider.
      parameters:
        - name: sessionid
          in: query
          description: The session id provided in the request to the gateway.
          required: true
          schema:
            type: string
          example: 'abcdefgh'
        - name: rqStatus
          in: query
          description: The status code
          required: true
          schema:
            type: integer
          example: 4
      responses:
        '202':
          description: Ok

components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"
    '404':
      description: "Not Found. This could be because: <br> * The organisation requested has been deleted or has never existed"
  schemas:
    smsResponse:
      type: object
      required:
        - reference
        - status
      properties:
        reference:
          description: Unique reference
          type: string
          format: uuid
          example: "5d950cbf-5a59-40f4-80dd-f7a25f3ac8bb"
        status:
          description: "Status for message. Valid values: Registered, Failed and Delivered"
          type: string
          example: Regsitered

    smsRequest:
      type: object
      required:
        - message
        - to
      properties:
        message:
          description: Message to send. It must contain a placeholder for the meeting link. The placeholder is called %meeting_url%. See example for an example.
          type: string
          example: "Access your meeting at %meeting_url%"
        to:
          description: Phone number to send message to.
          type: string
          example: "+4512345678"
    smsStatus:
      type: object
      required:
        - reference
        - status
      properties:
        reference:
          description: Unique reference
          type: string
          format: uuid
          example: "5d950cbf-5a59-40f4-80dd-f7a25f3ac8bb"
        status:
          description: "Status for message. Valid values: Registered, Failed and Delivered"
          type: string
          example: Regsitered

